### ISSUE TITLE
How to back to JS from IOS system setting page?

### ISSUE THREAD

**Issue by lianghuiyuan** [CookieCookson/cordova-plugin-settings#1]
You know, use the function "settings.openSettings();" truely can open IOS system setting page, but how to back to the last JS page from IOS system setting?

**Comment by CookieCookson** [comment]
The user will have to double-tap the home button to return back to the App for now. In iOS9 I now believe there will be a "Back to <appname>" in the status bar when you go between Apps. See:

http://willowtreeapps.com/blog/the-biggest-small-feature-of-ios-9/

**Comment by lianghuiyuan** [comment]
Sounds good! Look forward to this feature to be achieved. Thank you very much.
