### ISSUE TITLE
Can your provide some demo?

### ISSUE THREAD

**Issue by GavinNiezw** [CookieCookson/cordova-plugin-settings#2]
hi~,I use this plugins is not work,can your provide some demo? thanks!

**Comment by CookieCookson** [comment]
Hi @GavinNiezw I haven't actually done any maintenance or testing on this plugin for quite a while (8 months). I will test the plugin and see if there are any issues with it working on the newer Cordova / iOS versions. The plugin is really far too simple for me to warrant providing a demo though.

Also, could you let me know what error you are specifically having? It will help narrow down the issue you are having.

**Comment by CookieCookson** [comment]
@GavinNiezw - I have tested the plugin on the latest iOS and it works fine. If the Settings App opens but doesn't present your app's specific page, it is because you haven't requested any device-specific permissions and it doesn't need to have a page in the first place. Again, let me know the issue you are having and I am happy to help.

**Comment by GavinNiezw** [comment]
Hi @CookieCookson ,thank you for your reply.I have successfully using this plugin to open settings panel for the currently running App.But,This is not the result I want.I want to open ios system settings and open wifi settings.So,I have to go looking for other plugin.
Thanks for your help！

**Comment by CookieCookson** [comment]
@GavinNiezw - I've seen other people achieve what my plugin does plus much more so I would probably recommend using them anyway! See https://github.com/selahssea/Cordova-open-native-settings

**Comment by GavinNiezw** [comment]
@CookieCookson I have used than plugin,it runs successfully on Android,but, ios can't.Error message said 'the name of the ios without setting',such as WIFI.I see the document, there is no about the use of the ios,but the README.md  wrote to support ios.
