### ISSUE TITLE
Open settings via URI

### ISSUE THREAD

**Issue by pke** [CookieCookson/cordova-plugin-settings#3]
According to the cordova slack channel one can also use this plugin to open the settings via URI like this:

 `<a href="app-settings:">Open Settings</a>` 

One need to add this intent to the `config.xml` though:

`<allow-intent href="app-settings:" />`

Care to add this to the readme?

**Comment by CookieCookson** [comment]
Hmm, if `app-settings:` is now a thing, you probably don't even need this plugin to be added to perform the code above. It may not work on older versions of iOS however, so it's definitely worth testing out.

**Comment by pke** [comment]
I will test it :)
